projects:
  crk: "."

defaultProject: crk

pipeline:
  logRunningCommand: true

vcs:
  defaultBranch: main
  hooks:
    pre-push:
      - "moon run crk:branch-gate"
  remoteCandidates:
    - origin
  sync: true
